# Generated by Django 5.2.5 on 2025-08-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
